apiVersion: v1
kind: Service
metadata:
  name: client-node-srv
  # namespace: tickting
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - name: client
      protocol: TCP
      port: 4000
      targetPort: 4000
