apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: yelhadad/payments
          env:
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb://payments-mongo-srv:27017/payments
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              # value: sk_test_51KrLgrHrlHk1pkZJddbDKdgbKhYgnFox2cAT9IT7Dk4SUcuYhPlA9H4c6fqnhKluNGvv0m30TjMSMOxtQs1z6xQT00GxcnV9VH
              valueFrom:
                secretKeyRef:
                  name: stripe-key-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
