name: orders-deploy
# Controls when the workflow will run
on:
  push:
    branches:
      - "main"
    paths:
      - orders/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t yelhadad/orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push yelhadad/orders
      - uses: digitalocean/action-doctl@v2
        with: 
          token:
            ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing && kubectl rollout restart deployment orders-depl
          
      
      
      
      
      

