name: orders-deploy
# Controls when the workflow will run
on:
  push:
    branches:
      - "main"
    paths:
      - "infra/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with: 
          token:
            ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - run: cd infra
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl apply -f k8s/**
      - run: kubectl apply -f k8s-prod/**
          
      
      
      
      
      

