name: experation-deploy
# Controls when the workflow will run
on:
  workflow_dispatch: 
  push:
    branches:
      - "main"
    paths:
      - experation/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd experation && docker build -t yelhadad/experation .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push yelhadad/experation
      - uses: digitalocean/action-doctl@v2
        with: 
          token:
            ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing && kubectl rollout restart deployment experation-depl
          
      
      
      
      
      

